grpc:
  port: "4040"
kafka: 
  brokers:
  group_ids:
    orders: "scheduler-service-group-orders"
  topics:
    courier_requested: "courier.requested"
    refresh_token_deletion_requsted: "refresh_token.deletion.requested"
