services:
  postgres-db: 
    image: postgres:14-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  restaurants-service:
    build:
      context: .
      dockerfile: ./restaurants-service/Dockerfile
    container_name: restaurants-service
    restart: on-failure
    depends_on:
      - postgres-db
    ports:
      - "3001:3001"
      - "4040:4040"
    environment:
      - DB_SOURCE=postgresql://${DB_USER}:${DB_PASSWORD}@postgres-db:5432/${DB_NAME}?sslmode=disable
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - GRPC_SERVER=4040

  orders-db:
    image: postgres:14-alpine
    container_name: orders-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=orders
    ports:
      - "5433:5432"
    volumes:
      - orders-postgres-data:/var/lib/postgresql/data
  
  orders-service:
    build:
      context: .
      dockerfile: ./orders-service/Dockerfile
    container_name: orders-service
    restart: on-failure
    depends_on:
      - orders-db
      - kafka
    ports:
      - "3002:3002"
    environment:
      - DB_SOURCE=postgresql://${DB_USER}:${DB_PASSWORD}@orders-db:5432/orders?sslmode=disable
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - GRPC_SERVER=4040

  payments-service:
    build:
      context: .
      dockerfile: ./payments-service/Dockerfile
    container_name: payments-service
    restart: on-failure
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=${KAFKA_BROKERS}

  notification-service:
    build: 
      context: .
      dockerfile: ./notification-service/Dockerfile
    container_name: notification-service
    restart: on-failure
    depends_on: 
      - kafka
    environment:
      - KAFKA_BROKERS=${KAFKA_BROKERS}

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    restart: on-failure
    ports: 
      - "3000:3000"
    depends_on:
      - restaurants-service
    environment:
      - RESTAURANTS_SERVICE_URL=http://restaurants-service:3001
      - ORDERS_SERVICE_URL=http://orders-service:3002
    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

volumes:
  postgres-data:
  orders-postgres-data: