http:
  port: 3004
db:
  source: ""
kafka:
  brokers: ""
  group_ids:
    users: "users-service-group"
  topics:
    users_role_event: "users.role.event"
jwt:
  secret: ""
admin:
  email: ""
  password: ""