http:
  port: "3004"
grpc:
  port: "4040"
db:
  source: ""
kafka:
  brokers: ""
  group_ids:
    users: "users-service-group"
  topics:
    users_role_assigned: "users.role.assigned"
jwt:
  secret: ""
admin:
  email: ""
  password: ""