kafka:
  brokers: ""
  group_ids: 
    orders: "payments-service-group"
  topics:
    payment_succeeded: "payment.succeeded"
    payment_failed: "payment.failed"
    order_created: "order.created"
    order_updated: "order.updated"