grpc:
  port: "4040"
kafka:
  brokers: ""
  group_ids: 
    orders: "payments-service-group"
  topics:
    payment_succeeded: "payment.succeeded"
    payment_failed: "payment.failed"
    payment_requested: "payment.requested"